/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reputationSystemsSol from "./ReputationSystems.sol";
export type { reputationSystemsSol };
import type * as l1SloadSol from "./l1sload.sol";
export type { l1SloadSol };
export * as factories from "./factories";
export type { L2StorageForReputation } from "./l1sload.sol/L2StorageForReputation";
export { L2StorageForReputation__factory } from "./factories/l1sload.sol/L2StorageForReputation__factory";
export type { ReputationSystem } from "./ReputationSystems.sol/ReputationSystem";
export { ReputationSystem__factory } from "./factories/ReputationSystems.sol/ReputationSystem__factory";
